# Add support for postgress SQL database.
development:
  adapter: postgresql
  encoding: utf8
  database: my_database_development
  pool: 5
  username: firzan
  password: system

production:
  adapter: postgresql
  encoding: utf8
  database: my_database_development
  pool: 5
  username:
  password:
